title: Sagar Zoting
description: Personal Web Page
#author: Sagar Zoting
avatar: /logo.png
email: zotingsagar@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
paginate: 10
remote_theme: ngzhio/jekyll-theme-hamilton
# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 
# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:
# Jekyll
# ======
skin: midnight
subscribe: false

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: sagar__zoting
  card: summary
logo: logo.png
social:
  name: Sagar Zoting
  links:
    - https://twitter.com/Sagar__Zoting
    - https://www.facebook.com/zotingsagar
    - https://github.com/zotingsagar
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
